### ISSUE TITLE
Instagram feed has been failed

### ISSUE THREAD

**Issue by Ammet** [pavelk2/social-feed#184]
http://developers.instagram.com/post/145262544121/instagram-platform-update-effective-june-1-2016

Instagram feed on all my apps are crashed. Can this be this script issue? Or I should do something with Instagram app?

**Comment by ktaftaf** [comment]
Use this [link](http://instagramwordpress.rafsegat.com/docs/get-access-token/) to get an access token.

the first 8 digits of the access token is your user id. xxxxxxxx.shg638fhasjfbwejsfdsafbhds.....

then make sure you have these when initializing the feed:

`client_id: 'xxxxxxxxxxxxxxxxxx...',`
`user_id: xxxxxxxx,`
`access_token: 'xxxxxxxx.xxxxxxxxxxxxxxxxxx...',`

**Comment by andreabrunato** [comment]
@ktaftaf your solution don't work. Also, my access_token have more than 8 digits before the dot.

The console error from line 513 of jquery.socialfeed.js is "Uncaught TypeError: Cannot read property 'id' of undefined"

id refers to user id. I have generated a new access token from Instagram's developers website but the problem still there.

**Comment by andreabrunato** [comment]
Ok, I've solved by doing this:
- go to you Instagram developer clients, open the client an then in "Security" tab uncheck "Disable implicit OAuth"
- then go this url (change XXX to your client's data) and you will be redirected to you redirect_url page. 
  https://api.instagram.com/oauth/authorize/?client_id=XXX&redirect_uri=XXX&response_type=token&scope=public_content
- Copy the token generated as a parameter on the address bar
- use it in socialfeed's "access_token:"

**Comment by ktaftaf** [comment]
It works with my user account, however Im having trouble getting the above to work with hashtags.
It was my impression that "scope=public_content" is all that we needed to pull hashtags.
Is there something I'm missing?

I just read the discussion here https://github.com/stevenschobert/instafeed.js/issues/408

Seems this isn't going to be possible sadly.

**Comment by JohJohan** [comment]
@andreabrunato i am having the same problem, followd your steps but i dont get a genareted parameter on the address bar i get a 404 page. Do you have any sollutions?

Thank you

**Comment by ktaftaf** [comment]
@JohJohan you should be able to use Pixel Union's Token Generator http://instagram.pixelunion.net/

**Comment by JohJohan** [comment]
@ktaftaf Hello i did, but i still get Cannot read property 'id' of undefined, i have tried debuggin but couldnt figger out what was the problem

**Comment by ktaftaf** [comment]
@JohJohan Not sure whats going on then. I would make sure you have your User ID in there as well, it'll be the first 8 digits of the access token

```
            instagram:{
                accounts: ['@account'],
                limit: 10,
                user_id: insta_id,
                access_token: insta_token,
            },
```

**Comment by JohJohan** [comment]
@ktaftaf Thanks for repling, i call my functuion like this:
`
$('#instafeed').socialfeed({

```
    instagram:{
        accounts: ['@denderz_nl'],       //Array: Specify a list of accounts from which to pull posts
        limit: 9,                                                //Integer: max number of posts to load
        client_id: 'xxx',           //String: Instagram client id (option if using access token)
        access_token: 'xxx'                                         //String: Instagram access token
    }
```

`
And then some other templating the error is in social.feed.js on line 515
`
var url = Feed.instagram.api + 'users/' + user.id + '/media/recent/?' + authTokenParams + '&' + 'count=' + options.instagram.limit + '&callback=?';
`

Where can i find my instagram id?

**Comment by ktaftaf** [comment]
@JohJohan My guess would be that you should remove the "client_id" and replace with "user_id".
The first 8 of the access token you generated here http://instagram.pixelunion.net/ should be your "user_id"

e.g. 
`user_id: 19241354`
`access_token: '19241354.1677fd0.d8358b0e24c042d6952096383b3afffa'`

if that still gives you issues, make sure your user_id isnt in quotes so `xxxxxxxx` and not `'xxxxxxxx'`

**Comment by ktaftaf** [comment]
@JohJohan Apparently I was mistaken, the User id isnt the first 8 digits of the access token. Someone correct me if Im wrong, but I believe its all the digits until the first `.` in the Access Token

**Comment by JohJohan** [comment]
@ktaftaf I have tried to replace the client_id to user_id, and changede it to the didgets of my acces token still doesnt work.

**Comment by ktaftaf** [comment]
@JohJohan Sorry man, wish I could've been more help. Maybe someone else will see this thread and help you out. Im not sure what else to recommend.

**Comment by JohJohan** [comment]
@ktaftaf Thats okay, i thank you for trying :)

**Comment by pessato** [comment]
I'm very time poor, excuse the unprofessional comment however this may help someone. 

The api requests will not work if using @ in the accounts property of the Instagram settings ie: `accounts: ['@apple']` due to the updates of Instgrams API discussed above. If you are desperate to get this working before contributors can update this plugin you're going to need to edit the main file `jquery.socialfeed.js` 

line 483:
`url = Feed.instagram.api + 'users/search/?q=' + username + '&' + authTokenParams + '&count=1' + '&callback=?';`
change to
`url = Feed.instagram.api + 'users/self/?q=' + username + '&' + authTokenParams + '&count=1' + '&callback=?';`

line 515:
`var url = Feed.instagram.api + 'users/' + user.id + '/media/recent/?' + authTokenParams + '&' + 'count=' + options.instagram.limit + '&callback=?';`
change to
`var url = Feed.instagram.api + 'users/self/media/recent/?' + authTokenParams + '&' + 'count=' + options.instagram.limit + '&callback=?';`

This combined with adding the correct `access_token` and `user_id` plus ensuring you are the owner of the account you are trying to query should do the trick, working for me anyway.

**Comment by HartLarsson** [comment]
i've the original script workign simply getting from here:
https://www.instagram.com/developer/

```
CLIENT ID
CLIENT SECRET
WEBSITE URL
REDIRECT URI
SUPPORT EMAIL   
```

now using your CLIENT ID and REDIRECT URI call this url:

https://api.instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token
you will get the right TOKEN to use.

I've made this and all works.

**Comment by spairous** [comment]
I have the same issue and also noticed that the same problem exists in http://pavelk2.github.io/social-feed/ where I no longer see any Instagram posts returned for any tag that I use!

This seem to be a real issue that needs to be addressed by the plugin.

**Comment by HartLarsson** [comment]
is quite simple to discover why the demo of instagram not working. Look at the code and you will find why:

```
            // INSTAGRAM
            instagram: {
                accounts: queryTags,
                limit: 2,
                client_id: '88b4730e0e2c4b2f8a09a6184af2e218',
                access_token: ''
            },
```

the access_token is _clearly_ missing (pavel probably don't wanna share its own because many will not use their code: lazy people always around!)
