### ISSUE TITLE
Https:// Twitter and Facebook

### ISSUE THREAD

**Issue by goldenfire** [pavelk2/social-feed#245]
Anyone have any luck getting the resources to be pulled from secure locations as to prevent mixed insecure twitter assets on a secure site?

**Comment by martijngastkemper** [comment]
I thought I fixed that issue: 170f624510efe44f64b5528b965713a98e9b3a6e

Are use you use the latest version?

**Comment by goldenfire** [comment]
Interesting, I used Bower to install the script, and it looks like I'm using Version 0.1.2 yet the change from the issue you pointed to is not included in the package. the demo page https://pavelk2.github.io/social-feed-example/ is having the same issue as I am, where "The page at https://pavelk2.github.io/social-feed-example/ was allowed to display insecure content from http://pbs.twimg.com/tweet_video_thumb/C586JU1UwAApKE1.jpg." 

I will download the latest and see if it solves my issue. 
Thank you,

**Comment by goldenfire** [comment]
Latest version did solve my problem. Thank you for pointing me in the right direction.

**Comment by mutiullah7** [comment]
I've downloaded the latest version 0.1.2
it doesn't have the https code still gettings the mixed content for twitter feed.
